name: pluto_filtered_list
description: A List where filters can be applied to the List and elements can be accessed or modified in that state.
version: 0.0.1-alpha.3
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_filtered_list

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  collection: ^1.14.13

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.5.0
